SELECT
    c.CAR_ID,
    CASE 
        WHEN r.CAR_ID IS NOT NULL AND r.START_DATE <= '2022-10-16' AND r.END_DATE >= '2022-10-16' 
        THEN '대여중' 
        ELSE '대여 가능' 
    END AS AVAILABILITY
FROM
    (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) c
LEFT JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY r
    ON c.CAR_ID = r.CAR_ID 
    AND r.START_DATE <= '2022-10-16' 
    AND r.END_DATE >= '2022-10-16'
ORDER BY
    c.CAR_ID DESC;
