SELECT
    r.HISTORY_ID,
    FLOOR(
        CASE
            WHEN DATEDIFF(r.END_DATE, r.START_DATE) + 1 >= 90 THEN (DATEDIFF(r.END_DATE, r.START_DATE) + 1) * c.DAILY_FEE * (1 - dp90.DISCOUNT_RATE / 100.0)
            WHEN DATEDIFF(r.END_DATE, r.START_DATE) + 1 >= 30 THEN (DATEDIFF(r.END_DATE, r.START_DATE) + 1) * c.DAILY_FEE * (1 - dp30.DISCOUNT_RATE / 100.0)
            WHEN DATEDIFF(r.END_DATE, r.START_DATE) + 1 >= 7 THEN (DATEDIFF(r.END_DATE, r.START_DATE) + 1) * c.DAILY_FEE * (1 - dp7.DISCOUNT_RATE / 100.0)
            ELSE (DATEDIFF(r.END_DATE, r.START_DATE) + 1) * c.DAILY_FEE
        END
    ) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY r ON c.CAR_ID = r.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp7 ON c.CAR_TYPE = dp7.CAR_TYPE AND dp7.DURATION_TYPE = '7일 이상'
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp30 ON c.CAR_TYPE = dp30.CAR_TYPE AND dp30.DURATION_TYPE = '30일 이상'
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN dp90 ON c.CAR_TYPE = dp90.CAR_TYPE AND dp90.DURATION_TYPE = '90일 이상'
WHERE
    c.CAR_TYPE = '트럭'
ORDER BY
    FEE DESC,
    r.HISTORY_ID DESC;
