-- 코드를 입력하세요
SELECT
    b.CATEGORY,
    SUM(s.SALES) AS TOTAL_SALES
FROM
    BOOK b
JOIN
    BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE
    s.SALES_DATE >= '2022-01-01' AND s.SALES_DATE <= '2022-01-31'
GROUP BY
    b.CATEGORY
ORDER BY
    b.CATEGORY;